### ISSUE TITLE
Imported ManagementLockByScope does not match original

### ISSUE THREAD

**Issue by BoSoeborgPetersen** [pulumi/pulumi-azure-native#2144]
### What happened?

I wanted to remove a lock from the state and then import it, but because the scope is missing the starting slash, it has to be replaced after importing

### Steps to reproduce

I created a simple example to show the problem:
```
name: ImportError
description: A minimal Azure Native Pulumi YAML program
runtime: yaml

resources:
    rg:
        type: azure-native:resources:ResourceGroup
    lock:
        type: azure-native:authorization:ManagementLockByScope
        properties:
            level: ReadOnly
            scope: ${rg.id}
```
With it do the following steps:
- Create the resources
`pulumi up`
- Get lock id and urn
`pulumi stack -i -u`
- Remove the lock from the state 
`pulumi state delete 'urn:pulumi:dev::ImportError::azure-native:authorization:ManagementLockByScope::lock' --force`
- Import the lock
`pulumi import azure-native:authorization:ManagementLockByScope lock /subscriptions/<subscription_id>/resourceGroups/<resource_groups>/providers/Microsoft.Authorization/locks/<lock>`

### Expected Behavior

After import Pulumi should show no required changes

### Actual Behavior

Pulumi wants to replace the resources
![image](https://user-images.githubusercontent.com/11646592/208663248-9f8ebf91-d28d-47eb-82b4-ddfb9cf547dd.png)

### Output of `pulumi about`

CLI
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
yaml          unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in yaml

Current Stack: Bo_Petersen/ImportError/dev

TYPE                                              URN
pulumi:pulumi:Stack                               urn:pulumi:dev::ImportError::pulumi:pulumi:Stack::ImportError-dev
pulumi:providers:azure-native                     urn:pulumi:dev::ImportError::pulumi:providers:azure-native::default
azure-native:resources:ResourceGroup              urn:pulumi:dev::ImportError::azure-native:resources:ResourceGroup::rg
azure-native:authorization:ManagementLockByScope  urn:pulumi:dev::ImportError::azure-native:authorization:ManagementLockByScope::lock

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/Bo_Petersen
User           Bo_Petersen
Organizations  Bo_Petersen

No dependencies found

Pulumi locates its logs in C:\Users\BOSOBO~1\AppData\Local\Temp by default
warning: A new version of Pulumi is available. To upgrade from version '3.49.0' to '3.50.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
