### ISSUE TITLE
Support cognative services committment tiers with & without account

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-azure-native#2149]
We currently name resources using the `operationId` from the schema. This is usually in the form `[Resource]_[Operation]`

The following operation ids are available for commitment plans:

- `Microsoft.CognitiveServices/accounts/{accountName}/commitmentPlans/{commitmentPlanName}`
  - `CommitmentPlans_Get`
  - `CommitmentPlans_CreateOrUpdate`
  - `CommitmentPlans_Delete`
- `Microsoft.CognitiveServices/commitmentPlans/{commitmentPlanName}`
  - `CommitmentPlans_CreateOrUpdatePlan`
  - `CommitmentPlans_UpdatePlan`
  - `CommitmentPlans_DeletePlan`
  - `CommitmentPlans_GetPlan`

We use the first part (before `_`) as the resource name - de-pluralized - for the resource name. Therefore both of these endpoints resolve to the same resource name and conflict with each other.

## Aside on conflicting names

While investigating, I've generated a full list of conflicting resources:

`WebAppSourceControl` and `SiteSourceControl` both resolve to the path `Microsoft.Web/sites/{name}/sourcecontrols/web` - this may be a rename of the `operationId` between versions.

The following names are all attempted to be registered as resources multiple times:

```yaml
TagAtScope: /{scope}/providers/Microsoft.Resources/tags/default
AccountFilter: Microsoft.Media/mediaServices/{accountName}/accountFilters/{filterName}
Application: Microsoft.Solutions/applications/{applicationName}
ApplicationDefinition: Microsoft.Solutions/applicationDefinitions/{applicationDefinitionName}
Asset: Microsoft.Media/mediaServices/{accountName}/assets/{assetName}
AssetFilter: Microsoft.Media/mediaServices/{accountName}/assets/{assetName}/assetFilters/{filterName}
BackupShortTermRetentionPolicy: Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupShortTermRetentionPolicies/{policyName}
CommitmentPlan: Microsoft.CognitiveServices/commitmentPlans/{commitmentPlanName}
ConfigServer: Microsoft.AppPlatform/Spring/{serviceName}/configServers/default
Configuration: Microsoft.DBforMariaDB/servers/{serverName}/configurations/{configurationName}
Configuration: Microsoft.DBforMySQL/servers/{serverName}/configurations/{configurationName}
Configuration: Microsoft.DBforPostgreSQL/flexibleServers/{serverName}/configurations/{configurationName}
ContentKeyPolicy: Microsoft.Media/mediaServices/{accountName}/contentKeyPolicies/{contentKeyPolicyName}
Database: Microsoft.DBforMariaDB/servers/{serverName}/databases/{databaseName}
Database: Microsoft.DBforMySQL/servers/{serverName}/databases/{databaseName}
Database: Microsoft.Sql/servers/{serverName}/databases/{databaseName}
DatabaseBlobAuditingPolicy: Microsoft.Sql/servers/{serverName}/databases/{databaseName}/auditingSettings/{blobAuditingPolicyName}
EncryptionScope: Microsoft.Storage/storageAccounts/{accountName}/encryptionScopes/{encryptionScopeName}
FirewallRule: Microsoft.DBforMariaDB/servers/{serverName}/firewallRules/{firewallRuleName}
FirewallRule: Microsoft.DBforMySQL/servers/{serverName}/firewallRules/{firewallRuleName}
Gallery: Microsoft.Compute/galleries/{galleryName}
GalleryApplication: Microsoft.Compute/galleries/{galleryName}/applications/{galleryApplicationName}
GalleryApplicationVersion: Microsoft.Compute/galleries/{galleryName}/applications/{galleryApplicationName}/versions/{galleryApplicationVersionName}
GalleryImage: Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}
GalleryImageVersion: Microsoft.Compute/galleries/{galleryName}/images/{galleryImageName}/versions/{galleryImageVersionName}
JitRequest: Microsoft.Solutions/jitRequests/{jitRequestName}
Job: Microsoft.Media/mediaServices/{accountName}/transforms/{transformName}/jobs/{jobName}
MachineLearningCompute: Microsoft.MachineLearningServices/workspaces/{workspaceName}/computes/{computeName}
MediaService: Microsoft.Media/mediaservices/{accountName}
MonitoringSetting: Microsoft.AppPlatform/Spring/{serviceName}/monitoringSettings/default
Policy: Microsoft.Network/FrontDoorWebApplicationFirewallPolicies/{policyName}
PrivateEndpointConnection: Microsoft.MachineLearningServices/workspaces/{workspaceName}/privateEndpointConnections/{privateEndpointConnectionName}
Server: Microsoft.DBforMariaDB/servers/{serverName}
Server: Microsoft.DBforMySQL/servers/{serverName}
ServerAdministrator: Microsoft.DBforMySQL/servers/{serverName}/administrators/activeDirectory
ServerAdvisor: Microsoft.Sql/servers/{serverName}/advisors/{advisorName}
SiteSourceControl: Microsoft.Web/sites/{name}/sourcecontrols/web
StreamingLocator: Microsoft.Media/mediaServices/{accountName}/streamingLocators/{streamingLocatorName}
StreamingPolicy: Microsoft.Media/mediaServices/{accountName}/streamingPolicies/{streamingPolicyName}
Transform: Microsoft.Media/mediaServices/{accountName}/transforms/{transformName}
VirtualNetworkRule: Microsoft.DBforMariaDB/servers/{serverName}/virtualNetworkRules/{virtualNetworkRuleName}
VirtualNetworkRule: Microsoft.DBforMySQL/servers/{serverName}/virtualNetworkRules/{virtualNetworkRuleName}
WebAppSourceControl: Microsoft.Web/sites/{name}/sourcecontrols/web
WebAppSwiftVirtualNetworkConnection: Microsoft.Web/sites/{name}/networkConfig/virtualNetwork
WebAppSwiftVirtualNetworkConnectionSlot: Microsoft.Web/sites/{name}/slots/{slot}/networkConfig/virtualNetwork
Workspace: Microsoft.MachineLearningServices/workspaces/{workspaceName}
```

Related to:
- https://github.com/pulumi/pulumi-azure-native/pull/2147
