### ISSUE TITLE
Creating an AKS cluster returns a Kubeconfig that specifies device login

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-azure-native#2399]
### What happened?

I started with `pulumi new kubernetes-azure-typescript`. After adding on a K8s provider with the Kubeconfig returned from my AKS cluster and a K8s resource (see below), the following output appears in the CLI output ("To sign in,..."). :

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/410614/234071344-d7c29c63-e18d-44c5-9f61-2ad570e0d4d8.png">

After further investigation, the generated Kubeconfig specifies device login, which is why I'm seeing this:

```yaml
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQXRHZ0F3SUJBZ0lSQU1JYmIyQUhPY3AwbjdLNzVHMFhjakV3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdJQmNOTWpNd05ESTBNVGd5T1RNeVdoZ1BNakExTXpBME1qUXhPRE01TXpKYQpNQTB4Q3pBSkJnTlZCQU1UQW1OaE1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBCi9TZENONDdpTlljcGJkTUhmc1dLM1NGMTlXYUM4RlFmenhpTnpwVlpHcnp0bjhySWtjNHY2Y0pnZ1UxckJjalQKbW1LQWpKRDhnSEFybTJ3OTB1aDdxeXN0bzNHQ1luUSt2clZDaFpPd3ZJK284bVYvSndtMzBZZisxUXpQdlhHNgpQcm1zenFOYkRJQ25jbmpNa1JkVk4rZk56L2xwMDE0UXY2bk5iVzdmZVRKWEpOMlNpajZDSEJBTVFUbkdGdjFSCkpERUJxbTVIQ0dEK0kzakFkU1dOUUUzUE5VY3lzYTdYMU1XR2dGZ1d2WS9QTnBvNkNpNXVycVBmcnJQcENzOEkKRjVWWjd3NW5XQmhpWWNjclFob0duemVXa0VpTkZMdzk0TGIxNTZoa0NwWkN0VTQ5TU1Rbk1HdDFvbnlXeG9jdQpXUS9SSzlpTVdTR0Uyd1ErajdqU0toZkJmd1kzVllQT3d1TXA2K2tNSW1xY1RSVlVrRkZwU2xHc21JemFWRGdrClFDN1Mxd3ZqREcvcXFGdFpmZlB2MGZTV3Z3TTJnY2luRzJoRC9XLytLQTgzTTIyUHdMeDBVTExhNUR0aVlBN04KNFp6QkZOM2xPeWtiL2VEb1VnOCtRRTRTKzM1YjVwZFM4MmN3ODJHb2JoRHAxRVVkTVR4YVcxME5LQmlVNi9PKwpaQzdBUDVITWJ4VWYwK2hDTHd2RUduUUpjcWJCN0dEVllpQ1N1K003T21naHUxem5iUXU2azIzcnpvYTNjdFB0CkxwMEVJcWVQUE5hNHlvMFg0NTROQWpVUE5SZGo3Vk1lWlVDZ0ExRS9QanJ3dTljK21GQ09CT1dsaEE5WjFlNUwKUXdSOWd1L0VhTkJ6WjFtcGgxaFBKVWtLLzdlZ0pIYThwK0tmZXZHOC9YOENBd0VBQWFOQ01FQXdEZ1lEVlIwUApBUUgvQkFRREFnS2tNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGRXBpRE9vTHVWa3JEa1lxCnZ6RFBGaVAzSCtMd01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQkdZblVXSTdsczYydjRhWGc0dUt6SVFSUk0KSEM4dlEraWE2VlVqeFA3L3MrbWVLNUFvM0toTVZMWDBaU2htY2JPaUNaY0l5YlRaVkNWa0xFcFNvbjJra2ZPRApzTHdmdzY2dHNVOWVLUHVFVm1pMVZWTDRBUTlrSXNQUHJXODBtK0ZUaEJjVlhkT3dvM3dQcWFYSkM0em90a1JUCi9JNWlmWGpZTUFzdnNPajhPdFdRNUROdmNaVENvZUFRN1VyVEplTzlyRFV5VG1SbCs1T29Od0pDQVYyMUhqMFoKVDVVWUkwcXFoQTN3SFhqTE53QmhuQkdWVTM0d2pZUW5VTnZuUVNUcmhnQzUrL1ArZTlOcmNDUmFMWXEydE9XNQp5V2Z5OUpkTFpMcHdBK2lHMWtEVzg2K2FxWmVpNENaUU5MS0lQTUhIenpPSUJSUlAzaUpvMFpsVHVzWElhNDQ0Clp6dWFLQjIwU2Qrd2VXYU1jNjVvVENFeVJWUzAybjJHUkJZaHhOcFhTRnd6cmpyMElPanROWHBBWXRlTTVLM2MKM0Z5TmRvWk10M2JocGw4TzA0TDM1UWhaNjRGRCt5NFRlaDdJbVE4UWpveE5BWm91WCtqWkJ2ck9lVjUxamxRNgo5LzA4WDZWRDl0WFplWUFCdklHNEF4aHE4RDVlZU1kZFI2ZVpuSmJXQTFSbG5sQzhQTndhYkJTSmVGWjMzbEs4ClBOT0xCTzVRWGVWZ1ZiSVFSNVMvUERoZXBOZURvL2c5V2NTUEgrcDlVeGJNcGhYYVV4UDNRZUx0VEl6SE5jSzEKakdWZU9Fa0tJdGVHTW16VCt5MGpCR0JqNjNQb1hSaWtrbTY3MHNlN3A3bVl4MWRsTnB6bG9PL1plZS9zNDhzZwpJU2VMQ3hBSVdsaklYSUNYSnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://pulumi-nzg21zks.hcp.westus2.azmk8s.io:443
    name: managedCluster226b4617
contexts:
  - context:
      cluster: managedCluster226b4617
      user: clusterUser_resourceGroup3ce31ff7_managedCluster226b4617
    name: managedCluster226b4617
current-context: managedCluster226b4617
kind: Config
preferences: {}
users:
  - name: clusterUser_resourceGroup3ce31ff7_managedCluster226b4617
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - --environment
          - AzurePublicCloud
          - --server-id
          - 6dae42f8-4368-4678-94ff-3960e28e3630
          - --client-id
          - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
          - --tenant-id
          - 706143bc-e1d4-4593-aee2-c9dc60ab9be7
          - --login
          - devicecode
        command: kubelogin
        env: null
        provideClusterInfo: false
```

If I change to this, I can run `kubectl` commands from the CLI, but I'm still out of luck in creating Pulumi resources with the K8s provider. I will have to try another method or (GASP) programmatically alter the returned Kubeconfig:

```yaml
        args:
          - get-token
          - --environment
          - AzurePublicCloud
          - --server-id
          - 6dae42f8-4368-4678-94ff-3960e28e3630
          # - --client-id
          # - 80faf920-1908-4b52-b5ef-a8e7bedfc67a
          # - --tenant-id
          # - 706143bc-e1d4-4593-aee2-c9dc60ab9be7
          # - --login
          # - devicecode
          - --login
          - azurecli
        command: kubelogin
        env: null
        provideClusterInfo: false
```

I suspect that Azure's API response may have changed because I ran [a workshop on this](https://github.com/pulumi/workshops/blob/main/template-kubernetes-azure/csharp/module-03/README.md) some months ago, and the generated Kubeconfig worked just fine.

### Expected Behavior

n/a

### Steps to reproduce

n/a

### Output of `pulumi about`

```text
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.100.1
kubernetes    3.25.0
nodejs        unknown

Host     
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.5.0'

Current Stack: jkodrofftest/az-getting-started-k8s/dev

TYPE                                          URN
pulumi:pulumi:Stack                           urn:pulumi:dev::az-getting-started-k8s::pulumi:pulumi:Stack::az-getting-started-k8s-dev
pulumi:providers:azure-native                 urn:pulumi:dev::az-getting-started-k8s::pulumi:providers:azure-native::default_1_100_1
azure-native:resources:ResourceGroup          urn:pulumi:dev::az-getting-started-k8s::azure-native:resources:ResourceGroup::resourceGroup
azure-native:network:VirtualNetwork           urn:pulumi:dev::az-getting-started-k8s::azure-native:network:VirtualNetwork::virtualNetwork
azure-native:network:Subnet                   urn:pulumi:dev::az-getting-started-k8s::azure-native:network:Subnet::subnet1
azure-native:network:Subnet                   urn:pulumi:dev::az-getting-started-k8s::azure-native:network:Subnet::subnet2
azure-native:network:Subnet                   urn:pulumi:dev::az-getting-started-k8s::azure-native:network:Subnet::subnet3
azure-native:containerservice:ManagedCluster  urn:pulumi:dev::az-getting-started-k8s::azure-native:containerservice:ManagedCluster::managedCluster
pulumi:providers:kubernetes                   urn:pulumi:dev::az-getting-started-k8s::pulumi:providers:kubernetes::k8s-provider


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, jkodrofftest, zephyr, demo, pulumi

Dependencies:
NAME                  VERSION
@pulumi/kubernetes    3.25.0
@pulumi/pulumi        3.64.0
@types/node           16.18.24
@pulumi/azure-native  1.100.1

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
