### ISSUE TITLE
Invalid audience for Key Vault secret operations when using MSI

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-azure-native#2432]
```
error: keyvault.BaseClient#DeleteSecret: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized" Message="AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.azure.com/."
```

When using Managed Identity (ARM_USE_MSI) with the Pulumi Automation API. See #2374 for the original report. That issue is about the same error but using az CLI authentication, which was fixed.

**Comment by brucetan-displayr** [comment]
Having the same error, woudl be good if this is fixed

**Comment by thomas11** [comment]
I took a more in-depth look at this and unfortunately, it's due to a shortcoming in a dependency that we use that cannot be upgraded quickly. Related to #1464. We will try to schedule this workstream soon.

**Comment by thecodetinker** [comment]
Hello - we have just tried this with v2.75.0 and unfortunately got a different error. 

`error: keyvault.BaseClient#DeleteSecret: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized" Message="AKV10022: Invalid audience. Expected cfa8b339-82a2-471a-a3c9-0fc0be7a4093, found: https://management.azure.com/."`

The GUID represents the Key Vault Service Principal - it is registered as the same in all tenants (as per [this doc](https://learn.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys#service-principal-application-id)). Not sure if I need to open a new issue for this.

**Comment by thomas11** [comment]
Hi @thecodetinker, sorry for the additional trouble here. This is curious, as we have a CI test for secrets that passes, and I also just verified it locally using `az` user authentication. Maybe it's another MSI-specific issue. I'll look into testing that as soon as I can.

In the meantime, would you open a new issue please? It's helpful for tracking.

Here's my minimal attempted repro.

```yaml
name: azn-2374-delete-secret
runtime: yaml

config:
  tenantId:
    type: string
  objectId:
    type: string

resources:
  resourceGroup:
    type: azure-native:resources:ResourceGroup

  keyVault:
    type: azure-native:keyvault:Vault
    properties:
      resourceGroupName: ${resourceGroup.name}
      properties:
        sku:
          name: standard
          family: A
        tenantId: ${tenantId}
        accessPolicies:
          - tenantId: ${tenantId}
            objectId: ${objectId}
            permissions:
              secrets:
                - get
                - list
                - delete

  secret:
    type: azure-native:keyvault:Secret
    properties:
      resourceGroupName: ${resourceGroup.name}
      vaultName: ${keyVault.name}
      properties:
        value: mySecretValue
        attributes:
          enabled: true

outputs:
  vaultUri: ${keyVault.properties.vaultUri}
```
