### ISSUE TITLE
properties: Missing required property 'properties'

### ISSUE THREAD

**Issue by worldofgeese** [pulumi/pulumi-azure-native#2508]
### What happened?

The Azure Native provider appears to be stuck in a loop demanding `properties` when `properties` is defined unless I'm misunderstanding the error:

```console
❯ pulumi preview
Previewing update (dev)

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  azure-yaml-dev  create     6 messages


Diagnostics:
  pulumi:pulumi:Stack (azure-yaml-dev):
    Error: azure-native:keyvault:Vault is not assignable from {resourceGroupName: string, enableRbacAuthorization: boolean, tenantId: string, sku: {family: string, name: string}}
    Cannot assign '{resourceGroupName: string, enableRbacAuthorization: boolean, tenantId: string, sku: {family: string, name: string}}' to 'azure-native:keyvault:Vault':
      properties: Missing required property 'properties'
      Existing properties are: location, properties, vaultName, resourceGroupName, tags
      Existing properties are: tags, location, properties, vaultName, resourceGroupName
      Existing properties are: tags, location, vaultName, properties, resourceGroupName
```

I've tried removing fields 1-by-1 and even completely removing all key values from my `keyVault` object. In every case `properties` misses `properties`. Interestingly, it also appears to have an issue with `resourceGroupName` thinking it's both a key subordinate to `properties` and equal to. 

### Expected Behavior

Pulumi should create my project resources.

### Steps to reproduce

Use the Pulumi YAML provider and this Pulumi configuration:

```yaml
name: azure-yaml
runtime: yaml
description: Creates an Azure Active Directory Application, ApplicationPassword, ServicePrincipal, KeyVault, and a RoleAssignment.

resources:
  adApplication:
    type: azuread:Application
    properties:
      displayName: "MyApplication"

  applicationPassword:
    type: azuread:ApplicationPassword
    properties:
      applicationObjectId: ${adApplication.objectId}
      displayName: "MyApplicationPassword"
      endDateRelative: "8760h" # 1 year

  servicePrincipal:
    type: azuread:ServicePrincipal
    properties:
      applicationId: ${adApplication.applicationId}

  resourceGroup:
    type: azure-native:resources:ResourceGroup

  keyVault:
    type: azure-native:keyvault:Vault
    properties:
      resourceGroupName: ${resourceGroup.name}
      enableRbacAuthorization: true
      tenantId: edb7fc97-4792-4dc2-a129-b0e84d0a44bd
      sku:
        family: A
        name: standard

  roleAssignment:
    type: azure-native:authorization:RoleAssignment
    properties:
      principalId: ${servicePrincipal.id}
      principalType: ServicePrincipal
      roleDefinitionId: 4633458b-17de-408a-b874-0445c86b69e6
      scope: ${keyVault.id}

outputs:
  applicationPassword:
    value: ${applicationPassword.value}
  keyVaultId:
    value: ${keyVault.id}
```

### Output of `pulumi about`

```console
CLI          
Version      3.70.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
azuread       unknown
yaml          unknown

Host     
OS       arch
Version  "23.0.0"
Arch     x86_64

This project is written in yaml

Current Stack: worldofgeese/azure-yaml/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/worldofgeese
User           worldofgeese
Organizations  worldofgeese

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by worldofgeese** [comment]
I was able to solve by altering the configuration like so

```yaml
  keyVault:
    type: azure-native:keyvault:Vault
    properties:
      resourceGroupName: ${resourceGroup.name}
      properties:
        tenantId: edb7fc97-4792-4dc2-a129-b0e84d0a44bd
        enableRbacAuthorization: true
        sku:
          family: A
          name: standard
```

I'd still consider this odd behavior and maybe worth a rename somewhere 🤔
