### ISSUE TITLE
Creating AKS with BYOCNI results in cluster with kubenet plugin

### ISSUE THREAD

**Issue by zargha** [pulumi/pulumi-azure-native#2598]
### What happened?

When creating  Azure Kubernetes Cluster (AKS) cluster with [networkPlugin](https://www.pulumi.com/registry/packages/azure/api-docs/containerservice/kubernetescluster/#networkplugin_yaml): none, the cluster is created with kubenet plugin.

Pulumi.yaml
```
name: test
runtime: yaml
description: A Pulumi YAML program to deploy a Kubernetes cluster on Azure
config:
  azure-native:location:
    value: westeurope
  kubernetesVersion:
    type: string
    default: 1.24.3
  # The next two configuration values are required (no default can be provided)
  mgmtGroupId:
    type: string
  nodeVmSize:
    type: string
    default: Standard_DS2_v2
  numWorkerNodes:
    type: integer
    default: 3
  prefixForDns:
    type: string
    default: pulumi
  sshPubKey:
    type: string
outputs:
  # Export the Kubeconfig of the cluster
  clusterName: ${managedCluster.name}
  kubeconfig: ${actualKubeConfig}
resources:
  managedCluster:
    properties:
      aadProfile:
        # Supply the object ID of an existing Azure AD group to serve as cluster admins
        adminGroupObjectIDs:
          - ${mgmtGroupId}
        enableAzureRBAC: true
        managed: true
      addonProfiles: {}
      agentPoolProfiles:
        - availabilityZones: ["1"]
          count: ${numWorkerNodes}
          enableNodePublicIP: false
          mode: System
          name: systempool
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: ${nodeVmSize}
          #vnetSubnetID: ${subnet1.id}
      apiServerAccessProfile:
        authorizedIPRanges:
          - 0.0.0.0/0
        enablePrivateCluster: false
      dnsPrefix: ${prefixForDns}
      enableRBAC: true
      identity:
        type: SystemAssigned
      kubernetesVersion: ${kubernetesVersion}
      linuxProfile:
        adminUsername: azureuser
        ssh:
          publicKeys:
            - keyData: ${sshPubKey}
      networkProfile:
        networkPlugin: none
        networkPolicy: none
        #serviceCidr: 10.96.0.0/16
        #dnsServiceIP: 10.96.0.10
      resourceGroupName: ${resourceGroup.name}
    type: azure-native:containerservice:ManagedCluster
  # Create a new resource group
  resourceGroup:
    type: azure-native:resources:ResourceGroup
variables:
  actualKubeConfig:
    fn::fromBase64: ${aksCredentials.kubeconfigs[0].value}
  # Get the credentials for the AKS cluster created above
  aksCredentials:
    fn::azure-native:containerservice:listManagedClusterUserCredentials:
      resourceGroupName: ${resourceGroup.name}
      resourceName: ${managedCluster.name}

```
`az aks show` output:
```
az aks show -g resourceGroup7ef18428  -n managedCluster86dde975  | grep network
      "networkProfile": null,
  "networkProfile": {
    "networkDataplane": null,
    "networkMode": null,
    "networkPlugin": "kubenet",
    "networkPluginMode": null,
    "networkPolicy": null,
```

### Expected Behavior

The AKS cluster should not have kubenet as cni.

### Steps to reproduce

1. Create an AKS cluster using the following Pulumi.yaml file:
```
name: test
runtime: yaml
description: A Pulumi YAML program to deploy a Kubernetes cluster on Azure
config:
  azure-native:location:
    value: westeurope
  kubernetesVersion:
    type: string
    default: 1.24.3
  # The next two configuration values are required (no default can be provided)
  mgmtGroupId:
    type: string
  nodeVmSize:
    type: string
    default: Standard_DS2_v2
  numWorkerNodes:
    type: integer
    default: 3
  prefixForDns:
    type: string
    default: pulumi
  sshPubKey:
    type: string
outputs:
  # Export the Kubeconfig of the cluster
  clusterName: ${managedCluster.name}
  kubeconfig: ${actualKubeConfig}
resources:
  managedCluster:
    properties:
      aadProfile:
        # Supply the object ID of an existing Azure AD group to serve as cluster admins
        adminGroupObjectIDs:
          - ${mgmtGroupId}
        enableAzureRBAC: true
        managed: true
      addonProfiles: {}
      agentPoolProfiles:
        - availabilityZones: ["1"]
          count: ${numWorkerNodes}
          enableNodePublicIP: false
          mode: System
          name: systempool
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: ${nodeVmSize}
          #vnetSubnetID: ${subnet1.id}
      apiServerAccessProfile:
        authorizedIPRanges:
          - 0.0.0.0/0
        enablePrivateCluster: false
      dnsPrefix: ${prefixForDns}
      enableRBAC: true
      identity:
        type: SystemAssigned
      kubernetesVersion: ${kubernetesVersion}
      linuxProfile:
        adminUsername: azureuser
        ssh:
          publicKeys:
            - keyData: ${sshPubKey}
      networkProfile:
        networkPlugin: none
        networkPolicy: none
        #serviceCidr: 10.96.0.0/16
        #dnsServiceIP: 10.96.0.10
      resourceGroupName: ${resourceGroup.name}
    type: azure-native:containerservice:ManagedCluster
  # Create a new resource group
  resourceGroup:
    type: azure-native:resources:ResourceGroup
variables:
  actualKubeConfig:
    fn::fromBase64: ${aksCredentials.kubeconfigs[0].value}
  # Get the credentials for the AKS cluster created above
  aksCredentials:
    fn::azure-native:containerservice:listManagedClusterUserCredentials:
      resourceGroupName: ${resourceGroup.name}
      resourceName: ${managedCluster.name}
```
2. pulumi up

### Output of `pulumi about`

pulumi about
```
CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in yaml

Current Stack: zargha/foundations/k8s

TYPE                                          URN
pulumi:pulumi:Stack                           urn:pulumi:k8s::foundations::pulumi:pulumi:Stack::foundations-k8s
pulumi:providers:azure-native                 urn:pulumi:k8s::foundations::pulumi:providers:azure-native::default
azure-native:resources:ResourceGroup          urn:pulumi:k8s::foundations::azure-native:resources:ResourceGroup::resourceGroup
azure-native:containerservice:ManagedCluster  urn:pulumi:k8s::foundations::azure-native:containerservice:ManagedCluster::managedCluster


Found no pending operations associated with k8s

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zargha
User           zargha
Organizations  zargha

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This looks like an azure-native validation issue and a misunderstanding of yaml. "none" isn't a special value in yaml, it's just the string "none". So that's got what sent to azure, but I'm surprised the azure provider didn't error that it was an invalid value for networkPlugin.

**Comment by thomas11** [comment]
In this case, "none" wasn't meant to be a special value, the string "none" is actually one of the valid values here:
```json
        "networkPlugin": {
          "type": "string",
          "enum": [
            "azure",
            "kubenet",
            "none"
          ],
          "default": "kubenet",
```
(specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-05-01/managedClusters.json)

So now the question is where it went wrong.

**Comment by thomas11** [comment]
Hi @zargha, when you say "the cluster is created with kubenet plugin", did you observe this in the Azure portal per chance?

I tried to repro with a Typescript program where I specified
```ts
    networkProfile: {
        networkPlugin: "none",
    }
```

I ran `pulumi up` with --verbose=9 logging that shows all Azure requests and responses. All of them, including the Azure responses, had `networkPlugin: "none"`.

Then, when I checked on the new cluster in the portal, it said
>Network type (plugin):	        Kubenet


However, the Azure API still agrees that it's "none":
```bash
$ az aks show --name azure-aks079e8268 -g azure-go-aks754383b9 | rg networkPlugin
    "networkPlugin": "none",
    "networkPluginMode": null,
```

So to me this seems like an Azure portal bug.

**Comment by zargha** [comment]
Hi @thomas11, yes I have observed this bug in the Azure Portal where creating an AKS without `networkPlugin` results in showing `Network type (plugin): Kubenet` in Azure Portal. This even happens when i create a cluster using az cli: 
`az aks create -l westeurope -g nokubenet -n aks-nokubenet --network-plugin none`

This will result in a cluster with nodes complaining about `container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized`, which is expected behavior and:
```
az aks show -n aks-nokubenet -g nokubenet | grep network              
      "networkProfile": {
  "networkProfile": {
    "networkDataplane": null,
    "networkMode": null,
    "networkPlugin": "none",
    "networkPluginMode": null,
    "networkPolicy": null,
```

But when I create a cluster using Pulumi YAML with `networkPlugin: "none"`, the nodes are Ready and I get this:
```
az aks show -g resourceGroup399f8a62 -n managedCluster7bbd1dfa | grep network  
      "networkProfile": null,
  "networkProfile": {
    "networkDataplane": null,
    "networkMode": null,
    "networkPlugin": "kubenet",
    "networkPluginMode": null,
    "networkPolicy": null,
```
I see you have used Typescript to create a cluster. I wonder if you use Pulumi YAML and see the same behavior as mine as I am not sure what am i doing wrong here.

**Comment by thomas11** [comment]
Hi @zargha, I got around to trying this in YAML. I took your program and made some small changes (see below):
  1. remove the AAD profile so I didn't need to set that up
  2. use an SSH key created by Pulumi

First, I noticed that with
```
        networkPlugin: none
        networkPolicy: none
```
I got "_NetworkPolicy is not supported for network plugin none_" from Azure.

When I commented `networkPolicy: none`, I could create the cluster. `az aks show` now shows
```
    "networkPlugin": "none",
    "networkPluginMode": null,
    "networkPolicy": null,
```

So that worked as expected.  I don't have an explanation why you're seeing the swap to kubenet. It may have been a bug on the Azure side.

```yaml
name: azn-2598-aks-yaml
runtime: yaml
description: A Pulumi YAML program to deploy a Kubernetes cluster on Azure

config:
  azure-native:location:
    value: westus2
  kubernetesVersion:
    type: string
    default: 1.24.10
  nodeVmSize:
    type: string
    default: Standard_DS2_v2
  numWorkerNodes:
    type: integer
    default: 3
  prefixForDns:
    type: string
    default: pulumi

outputs:
  # Export the Kubeconfig of the cluster
  clusterName: ${managedCluster.name}
  kubeconfig: ${actualKubeConfig}

resources:
  sshKey:
    type: tls:PrivateKey
    properties:
      algorithm: "RSA"
      rsaBits: 4096
    
  managedCluster:
    properties:
      addonProfiles: {}
      agentPoolProfiles:
        - availabilityZones: ["1"]
          count: ${numWorkerNodes}
          enableNodePublicIP: false
          mode: System
          name: systempool
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: ${nodeVmSize}
      apiServerAccessProfile:
        authorizedIPRanges:
          - 0.0.0.0/0
        enablePrivateCluster: false
      dnsPrefix: ${prefixForDns}
      enableRBAC: true
      identity:
        type: SystemAssigned
      kubernetesVersion: ${kubernetesVersion}
      linuxProfile:
        adminUsername: azureuser
        ssh:
          publicKeys:
            - keyData: ${sshKey.publicKeyOpenssh}
      networkProfile:
        networkPlugin: none
        # networkPolicy: none
      resourceGroupName: ${resourceGroup.name}
    type: azure-native:containerservice:ManagedCluster
  
  resourceGroup:
    type: azure-native:resources:ResourceGroup

variables:
  actualKubeConfig:
    fn::fromBase64: ${aksCredentials.kubeconfigs[0].value}
  # Get the credentials for the AKS cluster created above
  aksCredentials:
    fn::azure-native:containerservice:listManagedClusterUserCredentials:
      resourceGroupName: ${resourceGroup.name}
      resourceName: ${managedCluster.name}
```
