### ISSUE TITLE
[OIDC] Can't use federated credentials in Azure DevOps

### ISSUE THREAD

**Issue by moredatapls** [pulumi/pulumi-azure-native#2884]
### What happened?

Azure DevOps provides three variables to connect to Azure using OIDC, as documented in the [AzureCLI task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines):

* tenantId
* servicePrincipalId
* idToken

Note that there's no URL like in GitHub.

I tried to follow [this example](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/) by Azure where they demonstrate the OIDC authentication with Terraform. In the example, they only specify `ARM_OIDC_TOKEN` and omit `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL`. When I do the same with Pulumi, it crashes with the following error message:

```
error: OIDC authentication was requested via useOidc/ARM_USE_OIDC but no token and/or
request URL were configured. See
https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#credentials for more information.
```

The error gets thrown [in this line](https://github.com/pulumi/pulumi-azure-native/blob/951c3ef92fc5e28f3f12fe3a77fdde3784905396/provider/pkg/provider/auth.go#L60C54-L60C54) because the Pulumi provider requires both the request URL and the request token to be set.

After looking through the [code of the Terraform AzureRM provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/640e4acd895e3802368746a8d947c55fa19e6c62/internal/provider/provider.go#L435) it seems to me that `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL` are used for some GitHub specific code, while the `ARM_OIDC_TOKEN` is used in cases where the token can be resolved through Azure AD directly (?).

I believe that the azure-native provider should **not** throw an error if _either_

* both `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL` are set _or_
* `ARM_OIDC_TOKEN` is set

### Example

1. Create a new Azure service connection in Azure DevOps that uses federated credentials
2. Add a Pulumi stack to your project
3. Add a pipeline to your project and add the following task:

```yaml
- task: AzureCLI@2
  displayName: "Pulumi up"
  inputs:
    azureSubscription: <service connection with federated credential>
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      export ARM_USE_OIDC=true
      export ARM_TENANT_ID="$tenantId"
      export ARM_CLIENT_ID="$servicePrincipalId"
      export ARM_OIDC_TOKEN="$idToken"
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
      
      pulumi up --yes --diff
```

### Output of `pulumi about`

```
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.17.0
dotnet        unknown
kubernetes    4.5.4

Host     
OS       darwin
Version  14.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='7.0.203'

Backend        
Name           ...
URL            azblob://pulumi-backend
User           ...
Organizations  
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.58.0
Pulumi.AzureNative  2.17.0
Pulumi.Kubernetes   4.5.4
```

### Additional context

Possibly related to #2868 and/or https://github.com/pulumi/pulumi/issues/14509

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
