### ISSUE TITLE
OIDC config not working

### ISSUE THREAD

**Issue by Arttii** [pulumi/pulumi-azure-native#3047]
### What happened?

I am trying to get the action working with an oidc setup for github. Azure cli is able to login in with OIDC. 
Any help would be really appreciated.

Edit: If i use a service principal credential(same app registration) instead of OIDC with the same permissions, it works. It is specifically failing when doing something with a `azure_native.app.v20230501.ContainerApp` resource. If I remove that resource it works out.
### Example

```
Run pulumi/actions@v4.4.0
  
Configured range: ^3
/usr/local/bin/pulumi version
v3.101.1
Pulumi version 3.101.1 is already installed on this machine. Skipping download
Logging into the Pulumi Cloud backend.
pulumi up on orgnologies/test
  Updating (orgnologies/test)
  
  
  View Live: https://app.pulumi.com/org/app-infra-app/test/updates/54
  
  
    pulumi:pulumi:Stack: (same)
      [urn=urn:pulumi:test::org-infra-app::pulumi:pulumi:Stack::org-infra-app-test]
  
  @ Updating....
  
  
      > pulumi:pulumi:StackReference: (read)
          [id=org/app-infra-base/test]
          [urn=urn:pulumi:test::org-infra-app::pulumi:pulumi:StackReference::org/app-infra-base/test]
          name: "org/app-infra-base/test"
  
  @ Updating....
  
  
  Resources:
      5 unchanged
  
  Duration: 36s
  
  
  /home/runner/work/_actions/pulumi/actions/v4.4.0/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77
                      : new CommandError(result);
  ^
  CommandError: code: -2
   stdout: 
   stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack orgnologies/test --non-interactive
  [resource plugin azure-native-2.23.0] installing
  error: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
  
  To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
  auth method - instructions for which can be found here: https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication
  
  Alternatively you can authenticate using the Azure CLI by using a User Account.
  Updating (org/test)
  
  View Live: https://app.pulumi.com/org/app-infra-app/test/updates/54
  
    pulumi:pulumi:Stack: (same)
      [urn=urn:pulumi:test::org-infra-app::pulumi:pulumi:Stack::org-infra-app-test]
  @ Updating....
      > pulumi:pulumi:StackReference: (read)
          [id=org/app-infra-base/test]
          [urn=urn:pulumi:test::org-infra-app::pulumi:pulumi:StackReference::org/app-infra-base/test]
          name: "org/app-infra-base/test"
  @ Updating....
  Resources:
      5 unchanged
  
  Duration: 36s
   err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --diff --exec-agent pulumi/actions@v3 --color auto --exec-kind auto.local --stack orgnologies/test --non-interactive
  [resource plugin azure-native-2.23.0] installing
  error: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
  
  To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
  auth method - instructions for which can be found here: https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication
  
  Alternatively you can authenticate using the Azure CLI by using a User Account.
  Updating (org/test)
  ```

### Output of `pulumi about`

Pulumi version 3.101.1
[resource plugin azure-native-2.23.0]

### Additional context

Workflow file looks like this:

```yaml
name: Pulumi Preview of App
on:
  pull_request:
        types: [opened, synchronize, reopened]
        branches:
          - master
  workflow_dispatch: 

env: 
  ORG: org
  STACK: test

defaults:
  run:
    working-directory: infra/app/

jobs:
    
    preview:
        # needs: changes
        # if: ${{needs.changes.outputs.changed == 'true'  }}
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        steps:
      
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: pnpm/action-setup@v2
          name: Install pnpm
          with:
            version: 7
            run_install: false
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'pnpm'

        - name: Install dependencies
          run: pnpm install .
   
         
        - name: Azure login
          uses: azure/login@v1.6.0   
         
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # - uses: pulumi/actions@v4
     
        - uses: pulumi/actions@v4
          with:
            command: preview
            stack-name: ${{ env.ORG }}/${{ env.STACK }} 
            comment-on-pr: true
            github-token: ${{ secrets.GITHUB_TOKEN }}
            work-dir: infra/app
            diff: true
           
          env:
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            ARM_USE_OIDC: true
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
           
           ```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @Arttii, sorry you're running into trouble here. It seems as if `ARM_USE_OIDC: true` has no effect but I cannot see why. Two thoughts:

1. I'm not sure what purpose the `azure/login` step serves in your workflow. You don't need it for Pulumi. Can you try removing it?
2. I can't see how the `ContainerApp` resource could be influencing this because the error happens at startup of the provider, before any resources are processed. Can you double-check it's the only difference between failing and successful configuration? Are you able to share a Pulumi program that reproduces the issue?

**Comment by mjeffryes** [comment]
closing as stale

**Comment by ReToCode** [comment]
We do see the same problem on our end. Can you please re-open this issue?

**Context**
* We have several resources using the "normal" pulumi azure-native provider, those work in both cases
* For `ContainerApps` we had to generate a version using the `2025-01-01` API with `pulumi package add azure-native app 2025-01-01`. On this provider, we see the above described issue. It works fine locally, when a normal user account is logged in with `az login` on a local shell. It stops working on CI with OIDC enabled.

Dependencies:
NAME                VERSION
Pulumi              3.83.2
Pulumi.AzureNative  3.5.1


**Issue description**
The `ContainerApps` resource fails with the following error:

```
 @ Refreshing....
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Service Principal / Client Certificate is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Service Principal / Client Secret is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if OIDC is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Managed Service Identity is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Obtaining a Multi-tenant token from the Azure CLI is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
      pulumi:pulumi:Stack <name> running debug: 2025/07/08 09:23:57 Using Obtaining a token from the Azure CLI for Authentication
 ~  azure-native_app_v20250101:app:ManagedEnvironment <name> refreshing (9s) error: obtain subscription(<guid>) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
   ~  azure-native_app_v20250101:app:ManagedEnvironment <name> **refreshing failed** error: obtain subscription(<guid>) from Azure CLI: parsing json result from the Azure CLI: waiting for the Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
      pulumi:pulumi:Stack <name> running error: update failed
      pulumi:pulumi:Stack <name> **failed** 1 error; 14 debugs
```

On the other resources, the login with OIDC works and looks like this:

```
  pulumi:pulumi:Stack <name>  debug: 2025/07/08 09:23:50 Testing if Service Principal / Client Secret is applicable for Authentication..
      pulumi:pulumi:Stack <name>  debug: 2025/07/08 09:23:50 Testing if OIDC is applicable for Authentication..
      pulumi:pulumi:Stack <name>  debug: 2025/07/08 09:23:50 Using OIDC for Authentication
      pulumi:pulumi:Stack <name>  debug: 2025/07/08 09:23:50 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant <tenant-guid>
 @ Refreshing.........
   ~  azure-native:authorization:RoleAssignment <name> refreshing (0s) 
```

The GitHub pipeline

```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Pulumi Login (OIDC)
        uses: pulumi/auth-actions@v1
        with:
          organization: xxx
          requested-token-type: xxx
          scope: xxx
       
      - name: Pulumi Refresh
        uses: pulumi/actions@v6
        with:
          command: refresh
          stack-name: xxx
          work-dir: xxx
          diff: true
          debug: true
        env:
          ARM_CLIENT_ID: xxx
          ARM_SUBSCRIPTION_ID: xxx
          ARM_TENANT_ID: xxx
          ARM_USE_OIDC: true
```

My current assumption is, that a generated provider somehow does not respect the `ARM_USE_OIDC` setting, or is unable to read the OIDC token that is available in its context. Then in the end it goes trough the other login options and prints an error about the `az login` which should not have been used in the first place. 

Please let me know if we can help debug this further.

Thanks and best,
Reto
