### ISSUE TITLE
"pulumi import" of a linux FunctionApp specifies  a kind that is not reproducible during "pulumi up"

### ISSUE THREAD

**Issue by nichitacebotari0** [pulumi/pulumi-azure-native#3055]
### What happened?

Im trying to create a functionapp that is run on linux by trying to reproduce an already existing functionapp in azure. 
The docs dont seem to specify much about the kind property(see https://github.com/pulumi/pulumi-hugo/issues/3892).

So I tried looking at the output of pulumi import which specifies `kind: "functionapp,linux"`, attempting to reproduce the same for a new function resource but it gets created as windows(screenshot from portal).
<img width="238" alt="Screenshot 2024-01-31 at 15 44 28" src="https://github.com/pulumi/pulumi-azure-native/assets/37653982/9cdeaa91-e517-49fb-a8a3-55188014112d">
Ive included the yaml and command output for the azure function below.

Note:This issue also seems to apply to app service plans so so Ive included the same set of info about the ASPs below, but if you'd like me to create a separate issue for ASP, please say. 

### Example

Pulumi import existing azure function:
`pulumi import azure-native:web:WebApp "function-prod" "/subscriptions/****resourceGroups/rg-function-prod/providers/Microsoft.Web/sites/function-prod" --diff`
```
 pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev]
    function-name: "function-dev"
    = azure-native:web:WebApp: (import) 🔒
        [id=/subscriptions/****/resourceGroups/rg-function-prod/providers/Microsoft.Web/sites/function-prod]
        [urn=urn:pulumi:dev::infrastructure::azure-native:web:WebApp::function-prod]
        clientAffinityEnabled     : false
        clientCertEnabled         : false
        clientCertMode            : "Required"
        containerSize             : 1536
        customDomainVerificationId: "****"
        dailyMemoryTimeQuota      : 0
        enabled                   : true
        hostNameSslStates         : [
            [0]: {
                hostType: "Standard"
                name    : "function-prod.azurewebsites.net"
                sslState: "Disabled"
            }
            [1]: {
                hostType: "Repository"
                name    : "function-prod.scm.azurewebsites.net"
                sslState: "Disabled"
            }
        ]
        hostNamesDisabled         : false
        httpsOnly                 : true
        hyperV                    : false
        identity                  : {
            type: "SystemAssigned"
        }
        isXenon                   : false
        keyVaultReferenceIdentity : "SystemAssigned"
        kind                      : "functionapp,linux"
        location                  : "West Europe"
        name                      : "function-prod"
        redundancyMode            : "None"
        reserved                  : true
        resourceGroupName         : "rg-function-prod"
        scmSiteAlsoStopped        : false
        serverFarmId              : "/subscriptions/****/resourceGroups/rg-function-prod/providers/Microsoft.Web/serverfarms/ASP-rgfunctionprod"
        siteConfig                : {
            acrUseManagedIdentityCreds : false
            alwaysOn                   : false
            functionAppScaleLimit      : 200
            http20Enabled              : false
            linuxFxVersion             : "DOTNET|6.0"
            minimumElasticInstanceCount: 0
            numberOfWorkers            : 1
        }
        storageAccountRequired    : false
        tags                      : {
            hidden-link: /app-insights-conn-string        : "InstrumentationKey=***;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/"
            hidden-link: /app-insights-instrumentation-key: "***"
            hidden-link: /app-insights-resource-id        : "/subscriptions/****/resourceGroups/rg-function-prod/providers/microsoft.insights/components/function-prod"
        }
        vnetContentShareEnabled   : false
        vnetImagePullEnabled      : false
        vnetRouteAllEnabled       : false
```

Pulumi import existing azure service plan:

`pulumi import azure-native:web:AppServicePlan "function-prod" "/subscriptions/****/resourceGroups/rg-function-prod/providers/Microsoft.Web/serverfarms/ASP-rgfunctionprod" --diff`
```
Previewing import (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev]
    function-name: "function-dev"
    = azure-native:web:AppServicePlan: (import) 🔒
        [id=/subscriptions/****/resourceGroups/rg-function-prod/providers/Microsoft.Web/serverfarms/ASP-rgfunctionprod]
        [urn=urn:pulumi:dev::infrastructure::azure-native:web:AppServicePlan::function-prod]
        elasticScaleEnabled      : false
        hyperV                   : false
        isSpot                   : false
        isXenon                  : false
        kind                     : "functionapp"
        location                 : "West Europe"
        maximumElasticWorkerCount: 1
        name                     : "ASP-rgfunctionprod"
        perSiteScaling           : false
        reserved                 : true
        resourceGroupName        : "rg-function-prod"
        sku                      : {
            capacity: 0
            family  : "Y"
            name    : "Y1"
            size    : "Y1"
            tier    : "Dynamic"
        }
        targetWorkerCount        : 0
        targetWorkerSizeId       : 0
        zoneRedundant            : false
```

`Pulumi.yaml` resources, trying to create new resources similar to the ones above:
```
resources:
  appServicePlan:
    type: azure-native:web:AppServicePlan
    properties:
      kind: "functionapp,linux"
      location: ${rg-function-dev.location}
      name: ASP-rgfunctiondev
      resourceGroupName: ${rg-function-dev.name}
      sku:
        name: Y1
        tier: Dynamic
        size: Y1
        family: Y
        capacity: 0
      
  
  function-dev:
    type: azure-native:web:WebApp
    options:
      dependsOn:
        - ${appServicePlan}
    properties:
      name: function-dev
      location: ${rg-function-dev.location}
      resourceGroupName: ${rg-function-dev.name}
      serverFarmId: ${appServicePlan.id} # app service plan id
      kind: "functionapp,linux"
      
        
  
# Imported already existing resources below:
  # Resource Group
  rg-function-dev:
    type: azure-native:resources:ResourceGroup
    properties:
      location: northeurope
      resourceGroupName: rg-function-dev
    options:
      protect: true
```

### Output of `pulumi about`

```
CLI          
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  unknown
yaml          unknown

Host     
OS       darwin
Version  13.5
Arch     arm64

This project is written in yaml

Current Stack: organization/infrastructure/dev

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev
pulumi:providers:azure-native         urn:pulumi:dev::infrastructure::pulumi:providers:azure-native::default
azure-native:resources:ResourceGroup  urn:pulumi:dev::infrastructure::azure-native:resources:ResourceGroup::rg-function-dev
azure-native:web:AppServicePlan       urn:pulumi:dev::infrastructure::azure-native:web:AppServicePlan::appServicePlan
azure-native:web:WebApp               urn:pulumi:dev::infrastructure::azure-native:web:WebApp::function-dev


Found no pending operations associated with dev

Backend        
Name           ncebotaris-MacBook-Air.local
URL            azblob://deployment-state?storage_account=storageaccountdev
User           ncebotari
Organizations  
Token type     personal

No dependencies found


```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
