### ISSUE TITLE
auto-created resource: WebAppSourceControlSlot

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-azure-native#3787]
### What happened?

Looks like the "slot" variant of "WebAppSourceControl" resource isn't marked as an auto-created resource.
```
Diagnostics:
  azure-native:web:WebAppSourceControlSlot (stagingContent):
    error: cannot create already existing resource '/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/rgdd0cc9be/providers/Microsoft.Web/sites/app54658a9e/slots/staging/sourcecontrols/web'
```

### Example

```yaml
name: upgrade-appservices-webapp
runtime: yaml
description: Upgrade test for web app services (AppServicePlan, WebApp)
variables:
  repoURL: https://github.com/Azure-Samples/app-service-web-html-get-started.git
  branch: master

resources:
  rg:
    type: azure-native:resources:ResourceGroup
  
  servicePlan:
    type: azure-native:web:AppServicePlan
    properties:
      kind: app
      resourceGroupName: ${rg.name}
      sku:
        name: S1

  app:
    type: azure-native:web:WebApp
    options:
      aliases:
        - "urn:pulumi:dev::upgrade-appservices::azure-native:web:WebApp::webApp"
    properties:
      kind: app
      resourceGroupName: ${rg.name}
      serverFarmId: ${servicePlan.id}

  appContent:
    type: azure-native:web:WebAppSourceControl
    properties:
      name: ${app.name}
      branch: ${branch}
      repoUrl: ${repoURL}
      resourceGroupName: ${rg.name}
      isManualIntegration: true
  
  appSettings:
    type: azure-native:web:WebAppApplicationSettings
    properties:
      name: ${app.name}
      resourceGroupName: ${rg.name}
      properties:
        sticky1: production
        setting1: v1

  appStickies:
    type: azure-native:web:WebAppSlotConfigurationNames
    properties:
      name: ${app.name}
      resourceGroupName: ${rg.name}
      appSettingNames:
        - sticky1

  staging:
    type: azure-native:web:WebAppSlot
    properties:
      name: ${app.name}
      slot: staging
      resourceGroupName: ${rg.name}
      serverFarmId: ${servicePlan.id}
      
  stagingContent:
    type: azure-native:web:WebAppSourceControlSlot
    options:
      dependsOn:
       - ${staging}
    properties:
      resourceGroupName: ${rg.name}
      name: ${app.name}
      slot: staging
      branch: v2
      repoUrl: ${repoURL}
      isManualIntegration: true

  stagingSettings:
    type: azure-native:web:WebAppApplicationSettingsSlot
    options:
      dependsOn:
       - ${staging}
    properties:
      resourceGroupName: ${rg.name}
      name: ${app.name}
      slot: staging
      properties:
        sticky1: staging
        setting1: v2

outputs:
  siteURL: https://${app.defaultHostName}/
```

### Output of `pulumi about`

```
❯ p about
CLI          
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  unknown
language  yaml          unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml
```

### Additional context

Related to: https://github.com/pulumi/pulumi-azure-native/pull/317

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
